/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafos;

import java.awt.event.ActionListener;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author gadia
 */
public class Interface extends javax.swing.JFrame implements ActionListener {
        
    public int matriz1 [][] = new int [5][5];   //Matriz de valores solo permite 1 y 0
    public int matriz2 [][] = new int [5][5];   //Matriz de signos solo permite '+','-' y '+/-' (1,2,3)
    public int x,y;
    public String val;
    

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JTX11 = new javax.swing.JTextField();
        JTX12 = new javax.swing.JTextField();
        JTX13 = new javax.swing.JTextField();
        JTX14 = new javax.swing.JTextField();
        JTX15 = new javax.swing.JTextField();
        JTX21 = new javax.swing.JTextField();
        JTX22 = new javax.swing.JTextField();
        JTX23 = new javax.swing.JTextField();
        JTX24 = new javax.swing.JTextField();
        JTX25 = new javax.swing.JTextField();
        JTX31 = new javax.swing.JTextField();
        JTX32 = new javax.swing.JTextField();
        JTX33 = new javax.swing.JTextField();
        JTX34 = new javax.swing.JTextField();
        JTX35 = new javax.swing.JTextField();
        JTX41 = new javax.swing.JTextField();
        JTX42 = new javax.swing.JTextField();
        JTX43 = new javax.swing.JTextField();
        JTX44 = new javax.swing.JTextField();
        JTX45 = new javax.swing.JTextField();
        JTX51 = new javax.swing.JTextField();
        JTX52 = new javax.swing.JTextField();
        JTX53 = new javax.swing.JTextField();
        JTX54 = new javax.swing.JTextField();
        JTX55 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFO A PARTIR DE UNA MATRIZ DE ADYACENCIA");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JTX11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX11.setText("0");
        JTX11.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTX11CaretUpdate(evt);
            }
        });
        JTX11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX11FocusLost(evt);
            }
        });
        JTX11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTX11ActionPerformed(evt);
            }
        });
        JTX11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTX11KeyTyped(evt);
            }
        });

        JTX12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX12.setText("0");
        JTX12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX12FocusLost(evt);
            }
        });

        JTX13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX13.setText("0");
        JTX13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX13FocusLost(evt);
            }
        });

        JTX14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX14.setText("0");
        JTX14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX14FocusLost(evt);
            }
        });

        JTX15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX15.setText("0");
        JTX15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX15FocusLost(evt);
            }
        });

        JTX21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX21.setText("0");
        JTX21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX21FocusLost(evt);
            }
        });

        JTX22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX22.setText("0");
        JTX22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX22FocusLost(evt);
            }
        });

        JTX23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX23.setText("0");
        JTX23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX23FocusLost(evt);
            }
        });

        JTX24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX24.setText("0");
        JTX24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX24FocusLost(evt);
            }
        });

        JTX25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX25.setText("0");
        JTX25.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX25FocusLost(evt);
            }
        });

        JTX31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX31.setText("0");
        JTX31.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX31FocusLost(evt);
            }
        });

        JTX32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX32.setText("0");
        JTX32.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX32FocusLost(evt);
            }
        });

        JTX33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX33.setText("0");
        JTX33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX33FocusLost(evt);
            }
        });

        JTX34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX34.setText("0");
        JTX34.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX34FocusLost(evt);
            }
        });

        JTX35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX35.setText("0");
        JTX35.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX35FocusLost(evt);
            }
        });

        JTX41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX41.setText("0");
        JTX41.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX41FocusLost(evt);
            }
        });

        JTX42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX42.setText("0");
        JTX42.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX42FocusLost(evt);
            }
        });

        JTX43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX43.setText("0");
        JTX43.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX43FocusLost(evt);
            }
        });

        JTX44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX44.setText("0");
        JTX44.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX44FocusLost(evt);
            }
        });

        JTX45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX45.setText("0");
        JTX45.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX45FocusLost(evt);
            }
        });

        JTX51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX51.setText("0");
        JTX51.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX51FocusLost(evt);
            }
        });

        JTX52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX52.setText("0");
        JTX52.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX52FocusLost(evt);
            }
        });

        JTX53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX53.setText("0");
        JTX53.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX53FocusLost(evt);
            }
        });

        JTX54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX54.setText("0");
        JTX54.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX54FocusLost(evt);
            }
        });

        JTX55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTX55.setText("0");
        JTX55.setToolTipText("");
        JTX55.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTX55FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A1");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("A4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("A3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("A5");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("A");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("B");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("D");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("C");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("E");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTX21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX23, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTX31, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX33, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX34, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX35, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTX41, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX42, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX43, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX44, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX45, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTX51, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX52, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX53, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX54, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX55, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTX11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(JTX15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTX11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTX21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTX31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTX41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTX51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTX55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(26, 26, 26))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("INGRESO DE DATOS");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("GRAFO RESULTANTE");

        JB1.setText("CALCULO");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB2.setText("REINICIO");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(113, 113, 113)
                        .addComponent(JB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB2))
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB1)
                        .addComponent(JB2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTX11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTX11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTX11ActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        
        //REINICIA LA MATRIZ
        for(int i=0;i<matriz1.length;i++)
        {
            for(int j=0; j<matriz1.length;j++){
                matriz1[i][j]=0;
                matriz2[i][j]=0;
            }
        }
        
        //DATOS JTX11
        if(JTX11.getText().equals("+1") || JTX11.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX11.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX11.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX11.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[0][0]=x;
        matriz2[0][0]=y;
        
        //DATOS JTX12
        if(JTX12.getText().equals("+1") || JTX12.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX12.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX12.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX12.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[0][1]=x;
        matriz2[0][1]=y;
        
        //DATOS JTX13
        if(JTX13.getText().equals("+1") || JTX13.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX13.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX13.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX13.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[0][2]=x;
        matriz2[0][2]=y;
        
        //DATOS JTX14
        if(JTX14.getText().equals("+1") || JTX14.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX14.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX14.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX14.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[0][3]=x;
        matriz2[0][3]=y;
        
        //DATOS JTX15
        if(JTX15.getText().equals("+1") || JTX15.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX15.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX15.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX15.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[0][4]=x;
        matriz2[0][4]=y;
        
        //DATOS JTX21
        if(JTX21.getText().equals("+1") || JTX21.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX21.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX21.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX21.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[1][0]=x;
        matriz2[1][0]=y;
        
        //DATOS JTX22
        if(JTX22.getText().equals("+1") || JTX22.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX22.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX22.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX22.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[1][1]=x;
        matriz2[1][1]=y;
        
        //DATOS JTX23
        if(JTX23.getText().equals("+1") || JTX23.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX23.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX23.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX23.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[1][2]=x;
        matriz2[1][2]=y;
        
        //DATOS JTX24
        if(JTX24.getText().equals("+1") || JTX24.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX24.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX24.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX24.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[1][3]=x;
        matriz2[1][3]=y;
        
        //DATOS JTX25
        if(JTX25.getText().equals("+1") || JTX25.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX25.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX25.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX25.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[1][4]=x;
        matriz2[1][4]=y;
        
        //DATOS JTX31
        if(JTX31.getText().equals("+1") || JTX31.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX31.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX31.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX31.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[2][0]=x;
        matriz2[2][0]=y;
        
        //DATOS JTX32
        if(JTX32.getText().equals("+1") || JTX32.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX32.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX32.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX32.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[2][1]=x;
        matriz2[2][1]=y;
        
        //DATOS JTX33
        if(JTX33.getText().equals("+1") || JTX33.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX33.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX33.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX33.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[2][2]=x;
        matriz2[2][2]=y;
        
        //DATOS JTX34
        if(JTX34.getText().equals("+1") || JTX34.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX34.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX34.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX34.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[2][3]=x;
        matriz2[2][3]=y;
        
        //DATOS JTX35
        if(JTX35.getText().equals("+1") || JTX35.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX35.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX35.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX35.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[2][4]=x;
        matriz2[2][4]=y;
        
        //DATOS JTX41
        if(JTX41.getText().equals("+1") || JTX41.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX41.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX41.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX41.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[3][0]=x;
        matriz2[3][0]=y;
        
        //DATOS JTX42
        if(JTX42.getText().equals("+1") || JTX42.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX42.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX42.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX42.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[3][1]=x;
        matriz2[3][1]=y;
        
        //DATOS JTX43
        if(JTX43.getText().equals("+1") || JTX43.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX43.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX43.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX43.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[3][2]=x;
        matriz2[3][2]=y;
        
        //DATOS JTX44
        if(JTX44.getText().equals("+1") || JTX44.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX44.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX44.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX44.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[3][3]=x;
        matriz2[3][3]=y;
        
        //DATOS JTX45
        if(JTX45.getText().equals("+1") || JTX45.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX45.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX45.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX45.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[3][4]=x;
        matriz2[3][4]=y;
        
        //DATOS JTX51
        if(JTX51.getText().equals("+1") || JTX51.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX51.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX51.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX51.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[4][0]=x;
        matriz2[4][0]=y;
        
        //DATOS JTX52
        if(JTX52.getText().equals("+1") || JTX52.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX52.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX52.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX52.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[4][1]=x;
        matriz2[4][1]=y;
        
        //DATOS JTX53
        if(JTX53.getText().equals("+1") || JTX53.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX53.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX53.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX53.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[4][2]=x;
        matriz2[4][2]=y;
        
        //DATOS JTX54
        if(JTX54.getText().equals("+1") || JTX54.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX54.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX54.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX54.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[4][3]=x;
        matriz2[4][3]=y;
        
        //DATOS JTX55
        if(JTX55.getText().equals("+1") || JTX55.getText().equals("1")){
            x=1;
            y=1;
        }else if(JTX55.getText().equals("-1")){
            x=1;
            y=2;            
        }else if(JTX55.getText().equals("+/-1")){
            x=1;
            y=3;
        }else if(JTX55.getText().equals("0")){
            x=0;
            y=0;
        }
        matriz1[4][4]=x;
        matriz2[4][4]=y;
        
        
        System.out.println("xxxxxx");
        System.out.println("m1");
        for(int i=0;i<5;i++)
        {
            for(int j=0; j<matriz1.length;j++){
                System.out.print(matriz1[i][j]+"-");
            }System.out.println("");
        }
        System.out.println("m2");
        for(int i=0;i<matriz2.length;i++)
        {
            for(int j=0; j<5;j++){
                System.out.print(matriz2[i][j]+"-");
            }System.out.println("");
        }
        
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
                JTX11.setText("0");
                JTX12.setText("0");
                JTX13.setText("0");
                JTX14.setText("0");
                JTX15.setText("0");
                JTX21.setText("0");
                JTX22.setText("0");
                JTX23.setText("0");
                JTX24.setText("0");
                JTX25.setText("0");
                JTX31.setText("0");
                JTX32.setText("0");
                JTX33.setText("0");
                JTX34.setText("0");
                JTX35.setText("0");    
                JTX41.setText("0");
                JTX42.setText("0");
                JTX43.setText("0");
                JTX44.setText("0");
                JTX45.setText("0");
                JTX51.setText("0");
                JTX52.setText("0");
                JTX53.setText("0");
                JTX54.setText("0");
                JTX55.setText("0");
    }//GEN-LAST:event_JB2ActionPerformed

    private void JTX11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTX11KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_JTX11KeyTyped

    private void JTX11CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTX11CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_JTX11CaretUpdate

    private void JTX11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX11FocusLost
        // TODO add your handling code here:
        val=JTX11.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
            JTX11.setText("0");
        }  
    }//GEN-LAST:event_JTX11FocusLost

    private void JTX12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX12FocusLost
        // TODO add your handling code here:
        val=JTX12.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX12.setText("0");            
        }  
    }//GEN-LAST:event_JTX12FocusLost

    private void JTX13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX13FocusLost
        // TODO add your handling code here:
        val=JTX13.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX13.setText("0");            
        }  
    }//GEN-LAST:event_JTX13FocusLost

    private void JTX14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX14FocusLost
        // TODO add your handling code here:
        val=JTX14.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX14.setText("0");            
        }  
    }//GEN-LAST:event_JTX14FocusLost

    private void JTX15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX15FocusLost
        // TODO add your handling code here:
        val=JTX15.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX15.setText("0");            
        }  
    }//GEN-LAST:event_JTX15FocusLost

    private void JTX21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX21FocusLost
        // TODO add your handling code here:
        val=JTX21.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX21.setText("0");            
        }  
    }//GEN-LAST:event_JTX21FocusLost

    private void JTX22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX22FocusLost
        // TODO add your handling code here:
        val=JTX22.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX22.setText("0");            
        }          
    }//GEN-LAST:event_JTX22FocusLost

    private void JTX23FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX23FocusLost
        // TODO add your handling code here:
        val=JTX23.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX23.setText("0");            
        }          
    }//GEN-LAST:event_JTX23FocusLost

    private void JTX24FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX24FocusLost
        // TODO add your handling code here:
        val=JTX24.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX24.setText("0");            
        }          
    }//GEN-LAST:event_JTX24FocusLost

    private void JTX25FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX25FocusLost
        // TODO add your handling code here:
        val=JTX25.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX25.setText("0");            
        }          
    }//GEN-LAST:event_JTX25FocusLost

    private void JTX31FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX31FocusLost
        // TODO add your handling code here:
        val=JTX31.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX31.setText("0");            
        }  
    }//GEN-LAST:event_JTX31FocusLost

    private void JTX32FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX32FocusLost
        // TODO add your handling code here:
        val=JTX32.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX32.setText("0");            
        }         
    }//GEN-LAST:event_JTX32FocusLost

    private void JTX33FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX33FocusLost
        // TODO add your handling code here:
        val=JTX33.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX33.setText("0");            
        }          
    }//GEN-LAST:event_JTX33FocusLost

    private void JTX34FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX34FocusLost
        // TODO add your handling code here:
        val=JTX34.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX34.setText("0");            
        }          
    }//GEN-LAST:event_JTX34FocusLost

    private void JTX35FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX35FocusLost
        // TODO add your handling code here:
        val=JTX35.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX35.setText("0");            
        }          
    }//GEN-LAST:event_JTX35FocusLost

    private void JTX41FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX41FocusLost
        // TODO add your handling code here:
        val=JTX41.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX41.setText("0");            
        }  
    }//GEN-LAST:event_JTX41FocusLost

    private void JTX42FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX42FocusLost
        // TODO add your handling code here:
        val=JTX42.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX42.setText("0");            
        }          
    }//GEN-LAST:event_JTX42FocusLost

    private void JTX43FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX43FocusLost
        // TODO add your handling code here:
        val=JTX43.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX43.setText("0");            
        }          
    }//GEN-LAST:event_JTX43FocusLost

    private void JTX44FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX44FocusLost
        // TODO add your handling code here:
        val=JTX44.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX44.setText("0");            
        }          
    }//GEN-LAST:event_JTX44FocusLost

    private void JTX45FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX45FocusLost
        // TODO add your handling code here:
        val=JTX45.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX45.setText("0");            
        }          
    }//GEN-LAST:event_JTX45FocusLost

    private void JTX51FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX51FocusLost
        // TODO add your handling code here:
        val=JTX51.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX51.setText("0");            
        }          
    }//GEN-LAST:event_JTX51FocusLost

    private void JTX52FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX52FocusLost
        // TODO add your handling code here:
        val=JTX52.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX52.setText("0");            
        }          
    }//GEN-LAST:event_JTX52FocusLost

    private void JTX53FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX53FocusLost
        // TODO add your handling code here:
        val=JTX53.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX53.setText("0");            
        }          
    }//GEN-LAST:event_JTX53FocusLost

    private void JTX54FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX54FocusLost
        // TODO add your handling code here:
        val=JTX54.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX54.setText("0");            
        }          
    }//GEN-LAST:event_JTX54FocusLost

    private void JTX55FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTX55FocusLost
        // TODO add your handling code here:
        val=JTX55.getText();
        
        if(val.equals("+1") || val.equals("1") || val.equals("-1") || val.equals("+/-1") || val.equals("0") ){        
        }else{
            JOptionPane.showMessageDialog(null, "Dato ingresado es incorrecto\nIngrese el valor de nuevo", "Error", JOptionPane.WARNING_MESSAGE);
        JTX55.setText("0");            
        }          
    }//GEN-LAST:event_JTX55FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JTextField JTX11;
    private javax.swing.JTextField JTX12;
    private javax.swing.JTextField JTX13;
    private javax.swing.JTextField JTX14;
    private javax.swing.JTextField JTX15;
    private javax.swing.JTextField JTX21;
    private javax.swing.JTextField JTX22;
    private javax.swing.JTextField JTX23;
    private javax.swing.JTextField JTX24;
    private javax.swing.JTextField JTX25;
    private javax.swing.JTextField JTX31;
    private javax.swing.JTextField JTX32;
    private javax.swing.JTextField JTX33;
    private javax.swing.JTextField JTX34;
    private javax.swing.JTextField JTX35;
    private javax.swing.JTextField JTX41;
    private javax.swing.JTextField JTX42;
    private javax.swing.JTextField JTX43;
    private javax.swing.JTextField JTX44;
    private javax.swing.JTextField JTX45;
    private javax.swing.JTextField JTX51;
    private javax.swing.JTextField JTX52;
    private javax.swing.JTextField JTX53;
    private javax.swing.JTextField JTX54;
    private javax.swing.JTextField JTX55;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
